const foodCategories = [
  'món xào',
  'món luộc',
  'món nướng',
  'món chiên',
  'món canh',
  'món nộm',
  'món gỏi',
  'món lẩu',
  'món nước',
  'món chính',
  'món ăn nhẹ',
  'món nhậu',
  'món hấp',
  'món trộn',
  'món chay',
  'món bánh',
  'món kho',
  'món cháo',
  'món ăn vặt',
  'món cuốn',
  'món dịp đặc biệt',
  'món giò',
  'món khai vị',
  'món salad',
  'món hầm',
  'món súp',
];

export default foodCategories;
